version: "3.8"

services:
  php-api-service:
    image: ghcr.io/smokesoulsorg/php-api-service:latest
    ports:
      - "8080:9000"  # Laravel artisan serve
    volumes:
      - ./.envs/php-api-service.env:/var/www/html/.env
    networks:
      - aylo
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: mysql
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d/z-replication.cnf:/etc/mysql/conf.d/z-replication.cnf
      - ./docker/mysql/init-replica-user.sql:/docker-entrypoint-initdb.d/99-init-replica-user.sql
    networks:
      - aylo
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-ppassword']
      retries: 3
      timeout: 5s
    restart: unless-stopped

  mysql_read:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: mysql_read
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3307:3306"
    volumes:
      - mysql_read_data:/var/lib/mysql
      - ./docker/mysql_read/conf.d/z-replication.cnf:/etc/mysql/conf.d/z-replication.cnf
      - ./docker/mysql_read/init-replication.sh:/docker-entrypoint-initdb.d/99-init-replication.sh
      - ./docker/mysql_read/init-sail-user.sql:/docker-entrypoint-initdb.d/99-init-sail-user.sql
    networks:
      - aylo
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-ppassword']
      retries: 3
      timeout: 5s
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aylo
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

networks:
  aylo:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  mysql_read_data:
    driver: local
  redis_data:
    driver: local
